### ISSUE TITLE
Can't download "leftImg8bit_sequence_trainvaltest.zip"

### ISSUE THREAD

**Issue by heng94** [D-Nilsson/GRFP#4]
Thanks for sharing the amazing work ,I have a proble that I can't the dataset named leftImg8bit_sequence_trainvaltest.zip as what you have written in the config .py . How can I solve the problem ? 
Thanks a lot !

**Comment by D-Nilsson** [comment]
Hi,

You need to go to the CityScapes website ([link](https://www.cityscapes-dataset.com/downloads/)), and then register and download leftImg8bit_sequence_trainvaltest.zip.

**Comment by Hanhanhan11** [comment]
@D-Nilsson 
Hi, I also can not download the dataset named leftImg8bit_sequence_trainvaltest.zip, this dataset  is available upon request. So, how do you get this dataset? How to request? I send email to cityscapes but have no reply.
Thank you very much.

**Comment by KaileyWoo** [comment]
> @D-Nilsson
> Hi, I also can not download the dataset named leftImg8bit_sequence_trainvaltest.zip, this dataset is available upon request. So, how do you get this dataset? How to request? I send email to cityscapes but have no reply.
> Thank you very much.

Hello, Is the problem solved?

**Comment by wangchuan** [comment]
I am faced with this problem right now. I sent the request but got no reply. Could you share any solution to it?

**Comment by KaileyWoo** [comment]
> I am faced with this problem right now. I sent the request but got no reply. Could you share any solution to it?

You should use a teacher email to send the request.

**Comment by kartikeya13** [comment]
Anybody knows what does http://leftimg8bit_sequence_trainvaltest.zip/ contains? are these just the raw images?
