### ISSUE TITLE
The problem with the function of get_GRU_cell

### ISSUE THREAD

**Issue by Hanhanhan11** [D-Nilsson/GRFP#6]
In get_GRU_cell, when to compute h = self.weights['lambda']*(1-z)*h_prev_reset + z*h_tilde, the wt is h_prev_reset, while in the paper, the h_prev_warped in the code represent wt, which one is right in computing the value of h in the code??

**Comment by D-Nilsson** [comment]
Hi, h_prev_reset in the code corresponds to r_t*w_t . See eq. 2 and 6 in [the paper](http://openaccess.thecvf.com/content_cvpr_2018/papers/Nilsson_Semantic_Video_Segmentation_CVPR_2018_paper.pdf). In an earlier arxiv version there was no multiplication by r.

**Comment by Hanhanhan11** [comment]
Hi, I see that h_prev_reset in the code corresponds to r_t*w_t,  but in the code, showed that h = self.weights['lambda']*(1 - z)*h_prev_reset + z*h_tilde where self.weights['lambda']*(1 - z) should multiply h_prev_warped which corresponds to w_t  in the paper.




At 2018-12-05 15:49:02, "D-Nilsson" <notifications@github.com> wrote:


Hi, h_prev_reset in the code corresponds to r_t*w_t . See eq. 2 and 6 in the paper. In an earlier arxiv version there was no multiplication by r.
