### ISSUE TITLE
Questions about parameters of flownet2 

### ISSUE THREAD

**Issue by yifanw90** [D-Nilsson/GRFP#7]
@D-Nilsson  Hi, thank you for the awesome work!  
From the project page, I download the pretrained model "Flownet2".  Are these parameters of flownet2  initialized from the caffe model of https://github.com/lmb-freiburg/flownet2 and fixed  or further finetuned on your data?
Looking forward to your reply.
Many Thanks!

**Comment by D-Nilsson** [comment]
Hi,

The flownet2 parameters are identical to those of the caffe model you referenced. It is not refined in the released code, but there are experiments in the CVPR paper where I did refine it.
